version: "3.3"
services:
  ops-challenge:
    image: gluzangi/img:cosmos-node
    build:
      context: .
      dockerfile: Dockerfile
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/tmp/ansible
